version: "3"

tasks:
  # Wailsアプリ の初期設定を行います
  init:
    cmds:
      # npmパッケージ のインストール & コード整形
      - cd frontend && npm ci
      - cd frontend && npm run format
      # Git 初期化 & 初回コミット
      - git init
      - git add .
      - git commit -m "🎉 init"
    silent: true

  # Wailsアプリ を開発モードで起動します
  dev:
    cmds:
      - wails dev
    silent: true

  # Wailsアプリ をビルドします
  build:
    cmds:
      - wails build
    silent: true

  # ソースコードの静的解析を実行します
  lint:
    cmds:
      - cd frontend && npm run lint
    silent: true

  # コードを整形します
  format:
    cmds:
      - cd frontend && npm run format
    silent: true

  # 単体テストを実施します
  test:
    cmds:
      - cd frontend && npm run test
    silent: true

  # Vitest UI を起動します
  test:ui:
    cmds:
      - cd frontend && npm run test:ui
    silent: true
